const API="https://api.postalpincode.in";const state={mode:"pincode"};
const tabs=document.querySelectorAll(".tab"),form=document.getElementById("searchForm"),input=document.getElementById("searchInput"),label=document.getElementById("searchLabel"),hint=document.getElementById("searchHint"),results=document.getElementById("results"),resultsTitle=document.getElementById("resultsTitle"),resultsMeta=document.getElementById("resultsMeta"),stats=document.getElementById("stats"),body=document.getElementById("resultsBody"),empty=document.getElementById("emptyState"),clearBtn=document.getElementById("clearBtn");
const modes={pincode:{label:"Enter 6-digit PIN Code",placeholder:"e.g. 314001",inputmode:"numeric",maxlength:6,hint:"Example: 314001"},postoffice:{label:"Enter Post Office Name",placeholder:"e.g. Dungarpur",inputmode:"text",maxlength:80,hint:"Example: Dungarpur"},location:{label:"Enter Location",placeholder:"e.g. Dungarpur",inputmode:"text",maxlength:80,hint:"Searches matching post office names returned by the public API."}};
tabs.forEach(tab=>tab.addEventListener("click",()=>{state.mode=tab.dataset.mode;tabs.forEach(t=>{const a=t===tab;t.classList.toggle("active",a);t.setAttribute("aria-selected",a?"true":"false")});const c=modes[state.mode];label.textContent=c.label;input.placeholder=c.placeholder;input.inputMode=c.inputmode;input.maxLength=c.maxlength;hint.textContent=c.hint;input.value="";input.focus()}));
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]??c))}
function badge(s){const d=String(s).toLowerCase()==="delivery";return '<span class="status '+(d?"delivery":"non")+'">'+esc(s||"Unknown")+"</span>"}
function render(data,query){body.innerHTML="";empty.hidden=true;if(!Array.isArray(data)||data.length===0){empty.hidden=false;resultsTitle.textContent="No results";resultsMeta.textContent="No matching post offices were returned.";stats.innerHTML="";return}resultsTitle.textContent=data.length===1?(data[0].Name||"Post office"):query;resultsMeta.textContent=data.length+" post office"+(data.length===1?"":"s")+" found";const districts=[...new Set(data.map(x=>x.District).filter(Boolean))];const delivery=data.filter(x=>String(x.DeliveryStatus).toLowerCase()==="delivery").length;stats.innerHTML=[["Total Offices",data.length],["Delivery",delivery],["Districts",districts.length]].map(([k,v])=>'<div class="stat"><span>'+esc(k)+'</span><strong>'+esc(v)+"</strong></div>").join("");body.innerHTML=data.map(r=>'<tr><td>'+esc(r.Name)+'</td><td>'+esc(r.Pincode)+'</td><td>'+esc(r.BranchType)+'</td><td>'+badge(r.DeliveryStatus)+'</td><td>'+esc(r.District)+'</td><td>'+esc(r.State)+'</td></tr>').join("");results.scrollIntoView({behavior:"smooth",block:"start"})}
async function search(path){const res=await fetch(API+path);if(!res.ok)throw new Error("API request failed");const p=await res.json();const first=Array.isArray(p)?p[0]:p;if(!first||first.Status!=="Success")return[];return Array.isArray(first.PostOffice)?first.PostOffice:[]}
form.addEventListener("submit",async e=>{e.preventDefault();const q=input.value.trim();if(!q)return;if(state.mode==="pincode"&&!/^\d{6}$/.test(q)){input.setCustomValidity("Please enter a valid 6-digit PIN code.");input.reportValidity();input.setCustomValidity("");return}const b=form.querySelector(".search-btn"),o=b.innerHTML;b.disabled=true;b.innerHTML="Searching…";try{const p=state.mode==="pincode"?"/pincode/"+encodeURIComponent(q):"/postoffice/"+encodeURIComponent(q);results.hidden=false;render(await search(p),q)}catch{results.hidden=false;resultsTitle.textContent="Search error";resultsMeta.textContent="The postal API could not be reached.";stats.innerHTML="";body.innerHTML="";empty.hidden=false;empty.textContent="Please try again in a moment."}finally{b.disabled=false;b.innerHTML=o}});
clearBtn.addEventListener("click",()=>{input.value="";results.hidden=true;input.focus()});
